create table student ( sno char(8), sage int, primary key (sage));
drop table student;
create index ssindex on student ( sno );
drop index ssindex;
select * from student;
insert into stu sut values ('asdf', 123, 12.11, -12, -123.12);
delete from stu where a > 2;
delete from stu where a >= 2;
delete from stu where a <= 2;
delete from stu where a < 2;
delete from stu where a == 2;
delete from stu where a <> 2;
quit;
