# -*-Python-*-

lib_target =  'recordmanager'
lib_sources =  [
    'Record.cpp',
    'RecordManager.cpp',
    ]

LIBS = [
    'logger',
    ]

LIBPATH = [
    '../logger',
    ]

env = Environment(CPPPATH = ['../', '.'])
env.Append(CXXFLAGS='-std=c++0x -Wall -O0 -g -gdwarf-2')
env.Library(target = lib_target,
            source = lib_sources,
            LIBS = LIBS, 
            LIBPATH = LIBPATH )
