# -*-Python-*-

lib_target =  'catelogmanager'
lib_sources =  [
    'CatelogManager.cpp'
    ]

LIBS = [
    'logger',
    ]


env = Environment(CPPPATH = ['../', '.'])
env.Append(CXXFLAGS='-std=c++0x -Wall -O2 -g -gdwarf-2')
env.Library(target = lib_target,
            source = lib_sources,
            LIBS = LIBS, 
            LIBPATH = ['../../logger', '../'])
