# -*-Python-*-

test_target =  'recordmanager_test'
test_sources =  [
    'RecordManager_test.cpp',
    'test_main.cpp',
    ]

LIBS = [
    'buffermanager',
    'logger',
    'recordmanager',
    ]

LIBPATH = [
    '../../buffermanager',
    '../../logger', 
    '../',
    ]

env = Environment(CPPPATH = ['../', '../../'])

env.Append(CXXFLAGS='-std=c++0x -Wall -O2 -g -gdwarf-2')
env.Program(target = test_target,
            source = test_sources,
            LIBS = LIBS, 
            LIBPATH = LIBPATH)

test = env.Command(target = 'test', 
                   source = [ test_target ],
                   action = './recordmanager_test')
env.AlwaysBuild(test)
