# -*-Python-*-

test_target =  'recordmanager_test'
test_sources =  [
    ]

LIBS = [
    ]

env = Environment(CPPPATH = ['../', '../../'])

env.Append(CXXFLAGS='-std=c++0x -Wall -O2 -g -gdwarf-2')
env.Program(target = test_target,
            source = test_sources,
            LIBS = LIBS, 
            LIBPATH = ['../../logger', '../'])
