# -*-Python-*-

lib_target =  'interpreter'

lib_sources =  [
    'InputHandler.cpp',
    'SQLScanner.cpp',
    'TokenAccepter.cpp',
    'SQLParser.cpp',
    'Token.cpp',
    ]

LIBS = [
    'logger',
    ]

env = Environment(CPPPATH = ['../'])
env.Append(CXXFLAGS='-std=c++0x -Wall -O2')
env.Library(target = lib_target, 
            source = lib_sources)
