# -*-Python-*-

lib_target =  'buffermanager'
lib_sources =  [
    'BufferManager.cpp',
    'FixedSizeChunkAllocator.cpp',
    'DbFile.cpp',
    'Page.cpp',                 
    ]

env = Environment(CPPPATH = ['../', '.'])
env.Append(CXXFLAGS='-std=c++0x -Wall -O0 -g -gdwarf-2')
env.Library(target = lib_target,
            source = lib_sources)
